# Generated by Django 4.0.4 on 2022-12-20 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('payee', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_household', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('household', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
