# Generated by Django 4.0.4 on 2022-12-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user',
            new_name='user_id',
        ),
    ]
