# Generated by Django 4.0.4 on 2022-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_remove_bill_user_bill_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
    ]
