# Generated by Django 4.0.4 on 2022-12-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_bill_secondary_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(default='internet', max_length=30),
            preserve_default=False,
        ),
    ]
