# Generated by Django 4.0.4 on 2022-12-11 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_bill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
