# Generated by Django 4.0.4 on 2022-12-12 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0008_bill_creation_date_bill_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='users',
        ),
        migrations.AddField(
            model_name='bill',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
