# Generated by Django 4.0.4 on 2022-12-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_open_invite'),
        ('authentication', '0002_rename_is_admin_flag_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='household',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='households.household'),
        ),
    ]
