# Generated by Django 4.0.4 on 2022-12-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_remove_household_member'),
        ('authentication', '0002_user_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='household',
        ),
        migrations.AddField(
            model_name='user',
            name='household_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='households.household'),
        ),
    ]
