# Generated by Django 4.0.4 on 2022-12-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_household_user_household_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='household_id',
        ),
    ]
