# Generated by Django 4.0.4 on 2022-12-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_open_invite'),
        ('authentication', '0003_alter_user_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='household',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='households.household'),
        ),
    ]
