# Generated by Django 4.0.4 on 2022-12-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_remove_household_admins_remove_household_members_and_more'),
        ('authentication', '0004_remove_user_household_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='household_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='households.household'),
        ),
    ]
