# Generated by Django 4.0.4 on 2022-12-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Goose', max_length=20),
            preserve_default=False,
        ),
    ]
