# Generated by Django 4.0.4 on 2022-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_household_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_household_admin',
            field=models.BooleanField(default=False),
        ),
    ]
