# Generated by Django 4.0.4 on 2022-12-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_is_household_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_household_admin',
            new_name='is_admin_flag',
        ),
    ]
