# Generated by Django 4.0.4 on 2022-12-08 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='secondaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
