# Generated by Django 4.0.4 on 2022-12-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_stock_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_level',
            new_name='stock_status',
        ),
    ]
