# Generated by Django 4.0.4 on 2022-12-09 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_product_secondary_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='secondary_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_secondaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
