# Generated by Django 4.0.4 on 2022-12-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_open_invite'),
        ('products', '0005_rename_stock_level_product_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.AddField(
            model_name='product',
            name='household',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='households.household'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_household',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
