# Generated by Django 4.0.4 on 2022-12-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='open_invite',
            field=models.BooleanField(default=False),
        ),
    ]
