# Generated by Django 4.0.4 on 2022-12-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='member',
        ),
    ]
