# Generated by Django 4.0.4 on 2022-12-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_remove_household_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='street_address',
            field=models.CharField(default='123 Washington Ave', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='zip',
            field=models.IntegerField(default=90210, max_length=30),
            preserve_default=False,
        ),
    ]
