# Generated by Django 4.0.4 on 2022-12-09 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0004_household_street_address_household_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='admins',
            field=models.ManyToManyField(related_name='primaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(related_name='secondaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='household',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
