# Generated by Django 4.0.4 on 2022-12-09 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0005_household_admins_household_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
