# Generated by Django 4.0.4 on 2022-12-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0006_alter_household_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
        migrations.RemoveField(
            model_name='household',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='household',
            name='zip',
        ),
    ]
