# Generated by Django 4.0.4 on 2022-12-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0008_household_address_household_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='household',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
