# Generated by Django 4.0.4 on 2022-12-09 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0009_alter_household_address_alter_household_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='admins',
            field=models.ManyToManyField(related_name='household_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='residents',
            field=models.ManyToManyField(related_name='household_residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
