# Generated by Django 4.0.4 on 2022-12-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0010_household_admins_household_residents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='household',
            name='residents',
        ),
    ]
