# Generated by Django 4.0.4 on 2022-12-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_open_invite'),
        ('categories', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='households.household'),
        ),
    ]
