# Generated by Django 4.0.4 on 2022-12-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_invites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joininvite',
            old_name='is_approved',
            new_name='is_accepted',
        ),
    ]
