# Generated by Django 4.0.4 on 2022-12-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_invites', '0002_rename_is_approved_joininvite_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joininvite',
            name='is_accepted',
        ),
    ]
