# Generated by Django 4.0.4 on 2022-12-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_invites', '0003_remove_joininvite_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joininvite',
            name='invite_number',
            field=models.CharField(max_length=8),
        ),
    ]
