# Generated by Django 4.0.4 on 2022-12-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_invites', '0004_alter_joininvite_invite_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joininvite',
            name='invite_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
