# Generated by Django 4.0.4 on 2022-12-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
