# Generated by Django 4.0.4 on 2022-12-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_requests', '0002_joinrequest_is_denied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='is_denied',
        ),
    ]
